[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
# NOTE: This line should be YOUR program ID, not the generic workspace ID.
# It should be the ID declared in your lib.rs (TDoetY1LKXn5vxxgkpE3keKhpRvbwHV6a2ep2Lreqov)
workspace = "TDoetY1LKXn5vxxgkpE3keKhpRvbwHV6a2ep2Lreqov" 

[registry]
url = "https://api.apr.dev"

[provider]
# 🔑 FIX: Change 'local-validator' to the standard local IP address.
cluster = "http://127.0.0.1:8899" 
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"